---
resources:
- name: le-opsman
  type: git
  source:
    uri: https://github.com/cdelashmutt-pivotal/le-opsman

- name: 1w
  type: time
  source: {interval: 168h}

jobs:
- name: le-retrieve
  plan:
  - get: 1w
    trigger: true
  - get: le-opsman
  - task: le-retrieve
    file: le-opsman/tasks/le-retreive.yml  
    params:
      GD_Key: ((gd-key))
      GD_Secret: ((gd-secret))
  - task: upload-material
    file: le-opsman/tasks/upload-material.yml
    params:
      OPSMAN_HOST: ((opsman-host))
      OPSMAN_USER: ((opsman-user))
      OPSMAN_PASSWORD: ((opsman-password))
