---
resources:
- name: le-opsman
  type: git
  source:
    uri: https://github.com/cdelashmutt-pivotal/le-opsman

- name: 1w
  type: time
  source: {interval: 168h}

jobs:
- name: get-opsman-cert
  plan:
  - get: 1w
    trigger: true
  - get: le-opsman
  - task: le-retrieve
    file: le-opsman/tasks/le-retrieve.yml
    params:
      GD_Key: ((gd-key))
      GD_Secret: ((gd-secret))
      HOSTNAMES: grogscave.net opsman.cf.grogscave.net
  - task: upload-material
    attempts: 5
    file: le-opsman/tasks/upload-material.yml
    params:
      OPSMAN_HOST: ((opsman-host))
      OPSMAN_USER: ((opsman-user))
      OPSMAN_PASSWORD: ((opsman-password))
- name: set-cf-haproxy-cert
  plan:
  - get: 1w
    trigger: true
  - get: le-opsman
  - task: le-retrieve-cf
    file: le-opsman/tasks/le-retrieve-cf.yml
    params:
      GD_Key: ((gd-key))
      GD_Secret: ((gd-secret))
      HOSTNAMES: cf.grogscave.net *.cf.grogscave.net *.uaa.cf.grogscave.net *.login.cf.grogscave.net
  - task: upload-material
    file: le-opsman/tasks/upload-material-credhub.yml
    attempts: 5
    params:
      CREDHUB_SERVER: ((credhub_server))
      CREDHUB_CA_CERT: ((credhub_ca_cert))
      CREDHUB_CLIENT: ((credhub_client))
      CREDHUB_SECRET: ((credhub_secret))
      KEY: /concourse/main/properties_networking_poe_ssl_certs_0_certificate
- name: set-concourse-cert
  plan:
  - get: 1w
    trigger: true
  - get: le-opsman
  - task: retrieve-concourse-certs
    file: le-opsman/tasks/le-retrieve.yml
    params:
      GD_Key: ((gd-key))
      GD_Secret: ((gd-secret))
      HOSTNAMES: concourse.cf.grogscave.net
  - task: upload-material
    attempts: 5
    file: le-opsman/tasks/upload-material-credhub.yml
    params:
      CREDHUB_SERVER: ((credhub_server))
      CREDHUB_CA_CERT: ((credhub_ca_cert))
      CREDHUB_CLIENT: ((credhub_client))
      CREDHUB_SECRET: ((credhub_secret))
      KEY: /bosh-control-plane/concourse/atc_tls