---
resources:
- name: version
  type: semver
  source:
    initial_version: 0
    driver: s3
    endpoint: ((s3-endpoint))
    bucket: ((s3-endpoint))
    key: version
    access_key_id: ((s3-access-key))
    secret_access_key: ((s3-secret-key))
    disable_ssl: true

- name: le-opsman
  type: git
  source:
    uri: https://github.com/cdelashmutt-pivotal/le-opsman
- name: crypto-material
  type: s3
  source:
    endpoint: ((s3-endpoint))
    bucket: ((s3-bucket))
    access_key_id: ((s3-access-key))
    secret_access_key: ((s3-secret-key))
    disable_ssl: true
    regexp: crypto-(.*).tgz

jobs:
- name: le-retrieve
  plan:
  - get: le-opsman
  - get: semver
    params:
      bump: major
  - task: le-retrieve
    file: le-opsman/tasks/le-retrieve.yml
    params:
      GD_Key: ((gd-key))
      GD_Secret: ((gd-secret))
  - put: crypto-material
  - put: semver
