---
resources:
- name: le-opsman
  type: git
  source:
    uri: https://github.com/cdelashmutt-pivotal/le-opsman

- name: 1w
  type: time
  source: {interval: 168h}

jobs:
- name: get-opsman-cert
  plan:
  - get: 1w
    trigger: true
  - get: le-opsman
  - task: le-retrieve
    file: le-opsman/tasks/le-retrieve.yml
    params:
      GD_Key: ((gd-key))
      GD_Secret: ((gd-secret))
  - task: upload-material
    file: le-opsman/tasks/upload-material.yml
    params:
      OPSMAN_HOST: ((opsman-host))
      OPSMAN_USER: ((opsman-user))
      OPSMAN_PASSWORD: ((opsman-password))
- name: set-cf-haproxy-cert
  plan:
  - get: 1w
    trigger: true
  - get: le-opsman
  - task: le-retrieve-cf
    file: le-opsman/tasks/le-retrieve-cf.yml
    params:
      GD_Key: ((gd-key))
      GD_Secret: ((gd-secret))
  - task: upload-material
    file: le-opsman/tasks/upload-material-cf.yml
    params:
      CREDHUB_SERVER: ((credhub_server))
      CREDHUB_CA_CERT: ((credhub_ca_cert))
      CREDHUB_CLIEN: ((credhub_client))
      CREDHUB_SECRET: ((credhub_secret))