---
resources:
- name: version
  type: semver
  source:
    initial_version: 0.0.0
    driver: s3
    endpoint: ((s3-endpoint))
    bucket: ((s3-bucket))
    key: version
    access_key_id: ((s3-access-key))
    secret_access_key: ((s3-secret-key))
    disable_ssl: true

- name: le-opsman
  type: git
  source:
    uri: https://github.com/cdelashmutt-pivotal/le-opsman
- name: crypto-material
  type: s3
  source:
    endpoint: ((s3-endpoint))
    bucket: ((s3-bucket))
    access_key_id: ((s3-access-key))
    secret_access_key: ((s3-secret-key))
    disable_ssl: true
    regexp: crypto-(.*).tgz

jobs:
- name: le-retrieve
  plan:
  - get: le-opsman
  - get: version
    params:
      bump: major
  - task: le-retrieve
    config:
      platform: linux
      
      image_resource:
        type: docker-image
        source:
          repository: neilpang/acme.sh
          tag: latest
      
      inputs:
      - name: le-opsman
      - name: version
        path: input-version
      
      outputs:
      - name: crypto-material
      - name: version
        
      run:
        path: ./le-opsman/tasks/le-retrieve.sh
      
      params:
        GD_Key:
        GD_Secret:
    params:
      GD_Key: ((gd-key))
      GD_Secret: ((gd-secret))
  - put: crypto-material
    params:
      file: crypto-material/crypto-*.tgz
  - put: version
    params:
      file: input-version/version
- name: apply-crypto-materials
  plan:
  - get: crypto-material
  - task: upload-material
    config:
      platform: linux
      image-resource:
        type: docker-image
          source: cdelashmutt/cf-automatuer
          tag: latest
      inputs:
      - name: crypto-material
      - name: le-opsman
      run:
        path: ./le-opsman/tasks/set-crypto-materials.sh
      params:
        OPSMAN_HOST:
        OPSMAN_USER:
        OPSMAN_PASSWORD:
    params:
      OPSMAN_HOST: ((opsman-host))
      OPSMAN_USER: ((opsman-user))
      OPSMAN_PASSWORD: ((opsman-password))
