---
resources:
- name: le-opsman
  type: git
  source:
    uri: https://github.com/cdelashmutt-pivotal/le-opsman

- name: 1w
  type: time
  source: {interval: 168h}

jobs:
- name: le-retrieve
  plan:
  - get: 1w
    trigger: true
  - get: le-opsman
  - task: le-retrieve
    config:
      platform: linux
      
      image_resource:
        type: docker-image
        source:
          repository: neilpang/acme.sh
          tag: latest
      
      inputs:
      - name: le-opsman
      
      outputs:
      - name: crypto-material
        
      run:
        path: ./le-opsman/tasks/le-retrieve.sh
      
      params:
        GD_Key: ((gd-key))
        GD_Secret: ((gd-secret))
  - task: upload-material
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cdelashmutt/cf-automatuer
          tag: latest
      inputs:
      - name: crypto-material
      - name: le-opsman
      run:
        path: ./le-opsman/tasks/set-crypto-materials.sh
      params:
        OPSMAN_HOST: ((opsman-host))
        OPSMAN_USER: ((opsman-user))
        OPSMAN_PASSWORD: ((opsman-password))
