---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cdelashmutt/cf-automatuer
    tag: latest

inputs:
- name: crypto-material
- name: le-opsman

run:
  path: ./le-opsman/tasks/set-crypto-material-cf.sh

params:
  CREDHUB_SERVER: 
  CREDHUB_CA_CERT:
  CREDHUB_CLIEN:
  CREDHUB_SECRET: